apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  type: NodePort
  ports:
  - port: 80           # Service port inside cluster
    targetPort: 80     # Container port
    nodePort: 30080    # External port on your Pi (must be between 30000–32767)
