apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-pvc
  namespace: website
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
