apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-html
data:
  index.html: |
    <html>
    <h1>Hello from Apache on K3s!</h1>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: web-content
        configMap:
          name: apache-html
