apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-html
  namespace: website
data:
  index.html: |
    <html>
      <head><title>K3s Apache Test</title></head>
      <body>
        <h1>Hello from Apache in the 'website' namespace!</h1>
      </body>
    </html>
