apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: website
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-storage
          mountPath: /home/manager/apache2/htdocs
      volumes:
      - name: apache-storage
        persistentVolumeClaim:
          claimName: apache-pvc
